### ISSUE TITLE
How to use this efi?

### ISSUE THREAD

**Issue by simonHIT** [vedant-y/dell-5559-hackintosh#1]
我的笔记本和你型号一致，请问怎么使用这份efi，有特殊的硬件更换吗？
my computer is dell-Inspiron-5559，too.So how do I use this efi ?Have you ever exchange any hardware to adjust this install?

**Comment by vedant-y** [comment]
Getting started with this EFI is pretty easy, I assume that you are currently using Windows OS and are about to create a bootable macOS installer drive.
- Download [macOS Catalina installer](https://mirrors.dtops.cc/iso/MacOS/daliansky_macos/) and [TransMac](https://www.acutesystems.com/scrtm.htm).
- Flash the macOS installer disk image with TransMac. You may need a 16 GB+ drive, since the installer alone is almost 8 GB.
- Mount the FAT formatted EFI partition manually, Windows may not mount it automatically. Also, Windows File Manager may not support accessing folders/files inside the EFI partition, [Explorer++](https://explorerplusplus.com/download) will be helpful in that case.
- Replace the EFI directory already present inside the mounted partition with the EFI folder in this repository.
- Finally, Reboot and F12. (Consider disabling secure boot before.)

I **have not** used any customized hardware to adjust the installation. Dell 5559 ships with Intel 3160 wireless adapter, macOS currently doesn't support it, so I use a Realtek wireless USB adapter with [drivers](https://github.com/chris1111/Wireless-USB-Adapter).

Sorry for not writing this in the README.md, I will update it soon.

**Comment by simonHIT** [comment]
Thanks for your anwser! I will try it.
